export type Status = 'Send' | 'Pending' | 'Response' | 'Ghosted';
export type Priority = 'Low' | 'Medium' | 'High' | 'Dream';
export type Warmth = 'Low' | 'Medium' | 'High';

export interface Interaction {
  id: string;
  date: string;
  type: 'sent' | 'received' | 'note' | 'meeting';
  content: string;
}

export interface Contact {
  id: string;
  name: string;
  company: string;
  role: string;
  linkedinUrl: string;
  email: string;
  inquiry: string;
  notes: string;
  status: Status;
  priority: Priority;
  score: number;
  warmth: Warmth;
  avatarColor: string;
  tags: string[];
  lastContacted: string;
  nextAction: string;
  actionNote?: string;
  aiSummary: string;
  outreachAngle: string;
  suggestedMessage: string;
  interactions: Interaction[];
}

export const mockContacts: Contact[] = [
  // ── To Send ──────────────────────────────────────────────
  {
    id: '12',
    name: 'Ali Hirsa',
    company: 'Columbia',
    role: 'Professor',
    linkedinUrl: 'https://linkedin.com/in/alihirsa',
    email: 'ah3005@columbia.edu',
    inquiry: 'Academic research in prediction markets and decision science',
    notes: 'Professor at Columbia running research on prediction markets. Key academic bridge.',
    status: 'Send',
    priority: 'Medium',
    score: 71,
    warmth: 'Low',
    avatarColor: 'bg-teal-200 text-teal-900',
    tags: ['Academic', 'Prediction Markets'],
    lastContacted: '2026-04-05',
    nextAction: 'Frame the ask around research direction, not a job.',
    actionNote: 'Frame the ask around research direction, not a job.',
    aiSummary: 'Ali Hirsa is a Columbia professor specializing in prediction markets and quantitative finance. His research overlaps directly with Orbit\'s core use case.',
    outreachAngle: 'Lead with academic curiosity — ask about his research on prediction market design, not your project.',
    suggestedMessage: 'Professor Hirsa — I\'ve been building in the prediction/sports market space and came across your research on market microstructure. Would love 15 minutes to understand how you think about prediction accuracy in thin markets.',
    interactions: [],
  },
  {
    id: '13',
    name: 'Jay Deuskar',
    company: 'PrizePicks',
    role: 'Growth',
    linkedinUrl: 'https://linkedin.com/in/jaydeuskar',
    email: 'jay@prizepicks.com',
    inquiry: 'Fantasy sports growth loops and user acquisition',
    notes: 'Growth lead at PrizePicks. Rare fantasy-sports operator contact. Very data-driven.',
    status: 'Send',
    priority: 'High',
    score: 88,
    warmth: 'Low',
    avatarColor: 'bg-blue-200 text-blue-900',
    tags: ['PrizePicks', 'Fantasy Sports'],
    lastContacted: '2026-02-16',
    nextAction: 'Lead with DraftIQ user-feedback ask.',
    actionNote: 'Rare fantasy-sports contact — lead with a DraftIQ user-feedback ask.',
    aiSummary: 'Jay runs growth at PrizePicks, one of the fastest-growing fantasy sports platforms. His growth playbook is directly applicable to Orbit\'s user acquisition strategy.',
    outreachAngle: 'You\'re building in his exact space. Ask for product feedback, not a favor — it\'s a lower-friction ask.',
    suggestedMessage: 'Hey Jay — I\'ve been building a sports prediction intelligence product and PrizePicks\' growth arc is one I think about constantly. Would you be open to 15 minutes to share what acquisition channels have surprised you most?',
    interactions: [],
  },
  {
    id: '14',
    name: 'Tarek Monsour',
    company: 'Kalshi',
    role: 'Markets',
    linkedinUrl: 'https://linkedin.com/in/tarekmonsour',
    email: 'tarek@kalshi.com',
    inquiry: 'Regulated prediction market operations',
    notes: 'Markets team at Kalshi. Knows the regulatory landscape deeply.',
    status: 'Send',
    priority: 'Medium',
    score: 64,
    warmth: 'Low',
    avatarColor: 'bg-indigo-200 text-indigo-900',
    tags: ['Kalshi', 'Prediction Markets'],
    lastContacted: '2026-02-02',
    nextAction: 'Short specific question about Kalshi\'s market-creation process.',
    aiSummary: 'Tarek is on Kalshi\'s markets team and understands CFTC compliance and market creation from the inside.',
    outreachAngle: 'Ask a very specific question about regulated market creation — specificity signals credibility.',
    suggestedMessage: 'Hey Tarek — quick question for someone in the weeds on this: when Kalshi creates a new market, who sets the initial pricing and what does the approval workflow look like? Building in the space and want to get this right.',
    interactions: [],
  },

  // ── Pending ───────────────────────────────────────────────
  {
    id: '1',
    name: 'Shayne Coplan',
    company: 'Polymarket',
    role: 'Founder & CEO',
    linkedinUrl: 'https://linkedin.com/in/shaynecoplan',
    email: 'shayne@polymarket.com',
    inquiry: 'Prediction market design and user growth',
    notes: 'Founded Polymarket at 22. Leading prediction market platform. Raised $70M+.',
    status: 'Pending',
    priority: 'Dream',
    score: 94,
    warmth: 'High',
    avatarColor: 'bg-orange-200 text-orange-900',
    tags: ['Polymarket', 'Prediction Markets'],
    lastContacted: '2026-05-29',
    nextAction: 'Follow up with value-add observation about prediction UX.',
    actionNote: 'High-priority, pending 10 days. Send a value-add follow-up, not a generic bump — cite one prediction-market UX observation.',
    aiSummary: 'Shayne is the CEO of Polymarket, the largest prediction market platform. He\'s deeply product-focused and mission-driven about information markets.',
    outreachAngle: 'Your work in the sports prediction space aligns with Polymarket\'s mission. Ask about market design philosophy and early liquidity.',
    suggestedMessage: 'Hey Shayne — I\'ve been building in the sports prediction space and Polymarket\'s market design is something I think about constantly. Would love 15 minutes to ask how you approached the early liquidity problem.',
    interactions: [
      { id: 'i1', date: '2026-05-29', type: 'sent', content: 'Sent cold LinkedIn message about prediction market design.' },
    ],
  },
  {
    id: '2',
    name: 'Sean Hargrow',
    company: 'Series',
    role: 'Founder',
    linkedinUrl: 'https://linkedin.com/in/seanhargrow',
    email: 'sean@series.so',
    inquiry: 'Early-stage startup building and fundraising',
    notes: 'Building Series, a fintech startup. Went through YC. Great operator mindset.',
    status: 'Pending',
    priority: 'High',
    score: 81,
    warmth: 'Medium',
    avatarColor: 'bg-orange-300 text-orange-900',
    tags: ['Series', 'VC / Funds'],
    lastContacted: '2026-05-29',
    nextAction: 'Short nudge with a specific question.',
    actionNote: 'Pending since 5/29 — a short nudge with a specific question lifts reply odds.',
    aiSummary: 'Sean is a YC founder building in fintech. Strong operator background, understands the grind of early-stage building.',
    outreachAngle: 'You\'re both building from scratch. Ask about the YC application process and early product focus.',
    suggestedMessage: 'Hey Sean — saw your work at Series and really admire how you\'ve approached the product. I\'m building Orbit and would love to pick your brain on early-stage focus.',
    interactions: [
      { id: 'i2', date: '2026-05-29', type: 'sent', content: 'Reached out via LinkedIn.' },
    ],
  },
  {
    id: '3',
    name: 'Baylor Adams',
    company: 'Z Fellows',
    role: 'Partner',
    linkedinUrl: 'https://linkedin.com/in/bayloradams',
    email: 'baylor@zfellows.com',
    inquiry: 'Z Fellows fellowship application and fit',
    notes: 'Runs Z Fellows, a fellowship for young builders. Could open major doors.',
    status: 'Pending',
    priority: 'Medium',
    score: 66,
    warmth: 'Low',
    avatarColor: 'bg-stone-300 text-stone-700',
    tags: ['Z Fellows', 'VC / Funds'],
    lastContacted: '2026-05-27',
    nextAction: 'Follow up on application status.',
    aiSummary: 'Baylor runs Z Fellows, a program for young ambitious founders. Key contact for fellowship access.',
    outreachAngle: 'Frame around your vision for Orbit and why you\'re building it now.',
    suggestedMessage: 'Hey Baylor — I\'ve been following Z Fellows for a while and I\'m really aligned with the mission. I\'m building Orbit and would love to share what I\'m working on.',
    interactions: [
      { id: 'i3', date: '2026-05-27', type: 'sent', content: 'Sent intro message about Z Fellows application.' },
    ],
  },
  {
    id: '4',
    name: 'Eric Liu',
    company: 'Totalis',
    role: 'Co-Founder & CEO',
    linkedinUrl: 'https://linkedin.com/in/ericliu',
    email: 'eric@totalis.io',
    inquiry: 'Sports data and prediction product design',
    notes: 'Building Totalis, a sports analytics platform. Columbia connection.',
    status: 'Pending',
    priority: 'Medium',
    score: 62,
    warmth: 'Medium',
    avatarColor: 'bg-emerald-200 text-emerald-900',
    tags: ['Sports Markets', 'Columbia'],
    lastContacted: '2026-05-26',
    nextAction: 'Schedule a call this week.',
    aiSummary: 'Eric is a technical founder building in sports analytics, direct overlap with Orbit\'s domain. Columbia alum — warm connection.',
    outreachAngle: 'Shared Columbia background + overlapping space makes this a natural peer conversation.',
    suggestedMessage: 'Hey Eric — fellow Columbia builder here. I\'ve been following Totalis and I\'m building in a similar adjacent space. Would love to compare notes.',
    interactions: [
      { id: 'i4', date: '2026-05-26', type: 'sent', content: 'Sent LinkedIn connection + message.' },
    ],
  },
  {
    id: '5',
    name: 'Calvin Smith',
    company: 'Novig',
    role: 'Head of Markets',
    linkedinUrl: 'https://linkedin.com/in/calvinsmith',
    email: 'calvin@novig.com',
    inquiry: 'Sports prediction market design and liquidity',
    notes: 'Head of Markets at Novig, a sports prediction exchange. Deep expertise in market microstructure.',
    status: 'Pending',
    priority: 'Medium',
    score: 60,
    warmth: 'Low',
    avatarColor: 'bg-cyan-200 text-cyan-900',
    tags: ['Novig', 'Prediction Markets'],
    lastContacted: '2026-05-26',
    nextAction: 'Follow up about market design conversation.',
    aiSummary: 'Calvin leads markets at Novig, one of the first licensed sports prediction exchanges in the US.',
    outreachAngle: 'Your interest in prediction/sports overlap is directly relevant.',
    suggestedMessage: 'Hey Calvin — I\'ve been digging deep into sports prediction market design and Novig\'s approach is fascinating. Would love 15 minutes to ask about market microstructure.',
    interactions: [
      { id: 'i5', date: '2026-05-26', type: 'sent', content: 'Cold outreach via LinkedIn.' },
    ],
  },

  // ── Responded ─────────────────────────────────────────────
  {
    id: '6',
    name: 'Oliver Wilson',
    company: 'Oracle Trading',
    role: 'Trader',
    linkedinUrl: 'https://linkedin.com/in/oliverwilson',
    email: 'oliver@oracletrading.com',
    inquiry: 'Quantitative trading and prediction markets',
    notes: 'Works on strategy at Oracle Trading. Responded quickly and was very helpful.',
    status: 'Response',
    priority: 'Medium',
    score: 55,
    warmth: 'Low',
    avatarColor: 'bg-blue-300 text-blue-900',
    tags: ['Oracle Trading', 'Prediction Markets'],
    lastContacted: '2026-04-09',
    nextAction: 'Send follow-up with Orbit deck.',
    aiSummary: 'Oliver responded positively and is well-connected in the quant/prediction space.',
    outreachAngle: 'He\'s already engaged — push toward a real conversation and ask for introductions.',
    suggestedMessage: 'Hey Oliver — following up on our last exchange. I\'ve made good progress on Orbit and would love to share the latest. Would you be open to a 20-minute call?',
    interactions: [
      { id: 'i6a', date: '2026-04-05', type: 'sent', content: 'Initial outreach about prediction markets.' },
      { id: 'i6b', date: '2026-04-09', type: 'received', content: 'Oliver replied positively, expressed interest.' },
    ],
  },
  {
    id: '15',
    name: 'Eugenio Garza',
    company: 'Polymarket',
    role: 'Product',
    linkedinUrl: 'https://linkedin.com/in/eugeniogarza',
    email: 'eugenio@polymarket.com',
    inquiry: 'Prediction market product design',
    notes: 'Product at Polymarket. Highly technical, great instincts on UX.',
    status: 'Response',
    priority: 'Medium',
    score: 62,
    warmth: 'Low',
    avatarColor: 'bg-teal-300 text-teal-900',
    tags: ['Polymarket', 'Prediction Markets'],
    lastContacted: '2026-03-07',
    nextAction: 'Follow up with specific product question.',
    aiSummary: 'Eugenio works on product at Polymarket and has deep insight into prediction market UX.',
    outreachAngle: 'Ask a specific product question about market resolution flows or user onboarding.',
    suggestedMessage: 'Hey Eugenio — thanks for your reply. One follow-up: how does Polymarket think about educating first-time users on market mechanics? It\'s a core challenge I\'m wrestling with.',
    interactions: [
      { id: 'i15a', date: '2026-03-03', type: 'sent', content: 'Cold outreach about product design.' },
      { id: 'i15b', date: '2026-03-07', type: 'received', content: 'Replied with brief but encouraging response.' },
    ],
  },
  {
    id: '16',
    name: 'Ronit Jain',
    company: 'Pluto',
    role: 'Founder',
    linkedinUrl: 'https://linkedin.com/in/ronitjain',
    email: 'ronit@pluto.so',
    inquiry: 'Early-stage building and VC / fundraising landscape',
    notes: 'Founder at Pluto. Went through a top accelerator. Well-networked in VC.',
    status: 'Response',
    priority: 'Medium',
    score: 70,
    warmth: 'Medium',
    avatarColor: 'bg-red-200 text-red-900',
    tags: ['Pluto', 'VC / Funds'],
    lastContacted: '2026-03-03',
    nextAction: 'Ask who else to talk to — he can unlock warm intros.',
    aiSummary: 'Ronit is a well-networked founder in the VC-backed startup world. Warm relationship with intro potential.',
    outreachAngle: 'He\'s responded — ask for introductions to investors or other founders in the space.',
    suggestedMessage: 'Hey Ronit — really appreciated your thoughts. One ask: is there anyone in your network you think I should talk to? Even one warm intro would mean a lot.',
    interactions: [
      { id: 'i16a', date: '2026-02-28', type: 'sent', content: 'Cold outreach about early-stage building.' },
      { id: 'i16b', date: '2026-03-03', type: 'received', content: 'Replied and was helpful, open to staying in touch.' },
    ],
  },
  {
    id: '10',
    name: 'Annie Dong',
    company: 'Dorm Room Fund',
    role: 'Partner',
    linkedinUrl: 'https://linkedin.com/in/anniedong',
    email: 'annie@dormroomfund.com',
    inquiry: 'Student venture funding and DRF application',
    notes: 'Partner at Dorm Room Fund. Had a great conversation. Very supportive of the vision.',
    status: 'Response',
    priority: 'High',
    score: 85,
    warmth: 'Medium',
    avatarColor: 'bg-pink-200 text-pink-900',
    tags: ['VC / Funds', 'Columbia'],
    lastContacted: '2026-01-29',
    nextAction: 'Send DRF application materials + follow-up.',
    aiSummary: 'Annie is a DRF partner who responded positively. A warm relationship with real funding potential.',
    outreachAngle: 'She\'s invested in student founders. Show her the Orbit progress and traction.',
    suggestedMessage: 'Hey Annie — hope you\'re well! Orbit has come a long way since we last connected. I think we\'re at the point where a DRF conversation makes sense.',
    interactions: [
      { id: 'i10a', date: '2026-01-25', type: 'sent', content: 'Cold outreach to DRF about Orbit.' },
      { id: 'i10b', date: '2026-01-29', type: 'received', content: 'Annie replied and said she\'d love to hear more.' },
    ],
  },
  {
    id: '11',
    name: 'Edward Tian',
    company: 'DraftKings',
    role: 'Product Manager',
    linkedinUrl: 'https://linkedin.com/in/edwardtian',
    email: 'edward@draftkings.com',
    inquiry: 'Fantasy sports product design and user engagement',
    notes: 'PM at DraftKings. Super helpful conversation about fantasy sports UX.',
    status: 'Response',
    priority: 'Medium',
    score: 58,
    warmth: 'Medium',
    avatarColor: 'bg-amber-200 text-amber-900',
    tags: ['Fantasy Sports', 'Gaming'],
    lastContacted: '2026-01-18',
    nextAction: 'Send follow-up with specific product questions.',
    aiSummary: 'Edward is a PM at DraftKings with direct domain expertise in fantasy sports UX.',
    outreachAngle: 'Lead with a specific product question about fantasy sports engagement.',
    suggestedMessage: 'Hey Edward — your insights have stuck with me. I had one more question: what\'s the number one thing that makes fantasy users come back daily vs. just seasonally?',
    interactions: [
      { id: 'i11a', date: '2026-01-15', type: 'sent', content: 'Cold outreach about fantasy sports product.' },
      { id: 'i11b', date: '2026-01-18', type: 'received', content: 'Edward replied with detailed thoughts on fantasy UX.' },
    ],
  },

  // ── Meeting ───────────────────────────────────────────────
  {
    id: '17',
    name: 'Eliam Medina',
    company: 'Telora',
    role: 'Founder',
    linkedinUrl: 'https://linkedin.com/in/eliammedina',
    email: 'eliam@telora.io',
    inquiry: 'Prediction markets and sports analytics product',
    notes: 'Founder at Telora, a sports analytics startup. Sharp thinker. Meeting booked.',
    status: 'Response',
    priority: 'Dream',
    score: 90,
    warmth: 'High',
    avatarColor: 'bg-emerald-300 text-emerald-900',
    tags: ['Telora', 'Prediction Markets'],
    lastContacted: '2026-03-05',
    nextAction: 'Prep 2 sharp questions on market structure before call.',
    actionNote: 'Meeting booked — prep 2 sharp questions on market structure.',
    aiSummary: 'Eliam is a founder in the sports analytics / prediction market space. Meeting booked — high value conversation.',
    outreachAngle: 'Show him Orbit\'s unique angle on prediction + sports data. Ask about his data sourcing.',
    suggestedMessage: 'Eliam — really looking forward to our call. I\'ll come prepared with two specific product questions about market structure. See you then.',
    interactions: [
      { id: 'i17a', date: '2026-02-28', type: 'sent', content: 'Cold outreach about prediction market overlap.' },
      { id: 'i17b', date: '2026-03-05', type: 'received', content: 'Replied and booked a meeting.' },
    ],
  },
  {
    id: '9',
    name: 'William Yoon',
    company: 'Entrepreneurs First',
    role: 'Investor',
    linkedinUrl: 'https://linkedin.com/in/williamyoon',
    email: 'william@joinef.com',
    inquiry: 'EF program application and founder matching',
    notes: 'Partner at EF. Responded very warmly. Has been helpful and offered to stay in touch.',
    status: 'Response',
    priority: 'Dream',
    score: 91,
    warmth: 'High',
    avatarColor: 'bg-violet-300 text-violet-900',
    tags: ['Entrepreneurs First', 'VC / Funds'],
    lastContacted: '2026-03-05',
    nextAction: 'Send update on Orbit progress + ask for EF application feedback.',
    actionNote: 'Ask who else to talk to — investors unlock warm intros fastest.',
    aiSummary: 'William is a key EF contact who has already expressed warmth. He can pipeline to the EF program and broader founder network.',
    outreachAngle: 'He\'s warm. Give him an update, show progress, and ask for his read on EF fit.',
    suggestedMessage: 'Hey William — wanted to send a quick update. Since we last spoke I\'ve made significant progress on Orbit. Would love to show you where things stand.',
    interactions: [
      { id: 'i9a', date: '2026-03-01', type: 'sent', content: 'Sent EF application inquiry.' },
      { id: 'i9b', date: '2026-03-05', type: 'received', content: 'William replied warmly, offered to stay in touch.' },
    ],
  },
  {
    id: '18',
    name: 'Andrew Kessler',
    company: 'Ornn',
    role: 'Founder',
    linkedinUrl: 'https://linkedin.com/in/andrewkessler',
    email: 'andrew@ornn.io',
    inquiry: 'Sports prediction product and B2B go-to-market',
    notes: 'Founder at Ornn, a sports intelligence startup. Meeting scheduled.',
    status: 'Response',
    priority: 'Dream',
    score: 89,
    warmth: 'High',
    avatarColor: 'bg-cyan-300 text-cyan-900',
    tags: ['Ornn', 'Prediction Markets'],
    lastContacted: '2026-02-16',
    nextAction: 'Bring data on Orbit\'s differentiator vs. Ornn to the call.',
    aiSummary: 'Andrew is building Ornn in a directly adjacent space. The conversation could surface competitive dynamics and potential collaboration.',
    outreachAngle: 'Be honest about the overlap and frame the conversation as peer-to-peer learning.',
    suggestedMessage: 'Andrew — excited for our call. I\'ll bring some data on how I\'m thinking about the sports prediction angle and would love your honest read on differentiation.',
    interactions: [
      { id: 'i18a', date: '2026-02-10', type: 'sent', content: 'Cold outreach about prediction market product.' },
      { id: 'i18b', date: '2026-02-16', type: 'received', content: 'Replied and booked a meeting.' },
    ],
  },

  // ── Ghosted ───────────────────────────────────────────────
  {
    id: '7',
    name: 'Nicholas Hull',
    company: 'Kalshi',
    role: 'Markets',
    linkedinUrl: 'https://linkedin.com/in/nicholashull',
    email: 'nicholas@kalshi.com',
    inquiry: 'Prediction market user growth and onboarding',
    notes: 'Leads growth at Kalshi. Ghosted after one message. Might try a different angle.',
    status: 'Ghosted',
    priority: 'High',
    score: 60,
    warmth: 'Medium',
    avatarColor: 'bg-purple-200 text-purple-900',
    tags: ['Kalshi', 'Prediction Markets'],
    lastContacted: '2026-03-07',
    nextAction: 'Try re-engagement with new angle or mutual connection.',
    actionNote: 'Ghosted 3mo. Send one value-add update, then archive.',
    aiSummary: 'Nick runs growth at Kalshi. Deep knowledge of how regulated prediction markets acquire users. Worth re-engaging.',
    outreachAngle: 'Try a different angle — lead with a specific question about regulated market UX, not your project.',
    suggestedMessage: 'Hey Nicholas — reaching back out with a specific question: how did Kalshi explain prediction markets to users who\'d never used one before?',
    interactions: [
      { id: 'i7', date: '2026-03-07', type: 'sent', content: 'Cold message about prediction markets. No response.' },
    ],
  },
  {
    id: '8',
    name: 'Kelechi Ukah',
    company: 'Novig',
    role: 'Operator',
    linkedinUrl: 'https://linkedin.com/in/kelechiukah',
    email: 'kelechi@novig.com',
    inquiry: 'Sports prediction exchange founding story',
    notes: 'Co-founded Novig. Columbia connection. Ghosted — maybe tried too hard.',
    status: 'Ghosted',
    priority: 'Medium',
    score: 67,
    warmth: 'Low',
    avatarColor: 'bg-amber-300 text-amber-900',
    tags: ['Novig', 'Sports Gaming'],
    lastContacted: '2026-03-06',
    nextAction: 'Short punchy re-engagement, lead with Columbia connection.',
    actionNote: 'Sports-betting + marketplace — worth one more DraftIQ-specific angle before archiving.',
    aiSummary: 'Kelechi co-founded Novig and is a Columbia alum. The ghost may have been message length.',
    outreachAngle: 'Keep it very short. Lead with Columbia connection and one specific question.',
    suggestedMessage: 'Hey Kelechi — fellow Columbia builder, keeping this short: what was the biggest thing you got wrong in year one at Novig?',
    interactions: [
      { id: 'i8', date: '2026-03-06', type: 'sent', content: 'Long cold message. No response.' },
    ],
  },
  {
    id: '19',
    name: 'Rhea Sanger',
    company: 'Kalshi',
    role: 'Markets',
    linkedinUrl: 'https://linkedin.com/in/rheasanger',
    email: 'rhea@kalshi.com',
    inquiry: 'Prediction market compliance and operations',
    notes: 'Markets at Kalshi. No response to initial outreach.',
    status: 'Ghosted',
    priority: 'Low',
    score: 44,
    warmth: 'Low',
    avatarColor: 'bg-rose-200 text-rose-900',
    tags: ['Kalshi', 'Prediction Markets'],
    lastContacted: '2026-01-30',
    nextAction: 'Archive or try once more with short note.',
    aiSummary: 'Rhea is on the markets team at Kalshi. No response — low priority re-engagement.',
    outreachAngle: 'One very short re-engagement; if no reply, archive.',
    suggestedMessage: 'Hey Rhea — quick question: what does Kalshi\'s market approval process look like from the inside? One sentence is totally fine.',
    interactions: [
      { id: 'i19', date: '2026-01-30', type: 'sent', content: 'Cold outreach. No response.' },
    ],
  },
];

export const columnConfig: Record<string, { dot: string; bg: string; text: string }> = {
  'Send':     { dot: 'bg-blue-500',    bg: 'bg-blue-50',    text: 'text-blue-700'    },
  'Pending':  { dot: 'bg-yellow-400',  bg: 'bg-amber-50',   text: 'text-amber-700'   },
  'Response': { dot: 'bg-emerald-500', bg: 'bg-emerald-50', text: 'text-emerald-700' },
  'Ghosted':  { dot: 'bg-red-500',     bg: 'bg-red-50',     text: 'text-red-700'     },
};

export const topicClusters = [
  { id: 'prediction-markets', name: 'Prediction Markets', contacts: 11, strength: 'strong', color: 'bg-emerald-600' },
  { id: 'vc-funds',           name: 'VC / Funds',         contacts: 6,  strength: 'strong', color: 'bg-emerald-600' },
  { id: 'sports-gaming',      name: 'Sports Gaming',      contacts: 3,  strength: 'medium', color: 'bg-amber-500'  },
  { id: 'operators',          name: 'Operators',          contacts: 3,  strength: 'medium', color: 'bg-amber-500'  },
  { id: 'fantasy-sports',     name: 'Fantasy Sports',     contacts: 2,  strength: 'weak',   color: 'bg-orange-500', gap: 'Your most relevant cluster for DraftIQ — and weakest.' },
  { id: 'legal-policy',       name: 'Legal / Policy',     contacts: 1,  strength: 'weak',   color: 'bg-orange-500', gap: 'Compliance matters for sports betting.' },
  { id: 'academic',           name: 'Academic',           contacts: 1,  strength: 'weak',   color: 'bg-emerald-600' },
];

export const networkGaps = [
  'Fantasy football commissioners',
  'DraftKings / FanDuel product alumni',
  'Campus sports creators',
  'Discord community owners',
];

export function getContactById(id: string): Contact | undefined {
  return mockContacts.find(c => c.id === id);
}
